identifier = "contains"
category = "built-in"
markdown = """
# contains
---
> category: [Built-ins for strings](https://freemarker.apache.org/docs/ref_builtins_string.html#ref_builtin_contains)
---
> __Note:__
> This built-in is available since FreeMarker 2.3.1. It doesn't exist in 2.3.

Returns if the substring specified as the parameter to this built-in occurrs in the string. For example:
```template
<#if "piceous"?contains("ice")>It contains "ice"</#if>
```
The output will be:
```output
It contains "ice"
```
"""
