identifier = "is_hash"
category = "built-in"
markdown = """
# is_hash
---
> category: [Seldom used and expert built-ins](https://freemarker.apache.org/docs/ref_builtins_expert.html#ref_builtin_isType)
---
These built-ins check the type of a variable, and returns `true` if the value is a hash (including extended hash).
"""