identifier = "is_string"
category = "built-in"
markdown = """
# is_string
---
> category: [Seldom used and expert built-ins](https://freemarker.apache.org/docs/ref_builtins_expert.html#ref_builtin_isType)
---
These built-ins check the type of a variable, and returns `true` if the value is a string.
"""