category = "directive"
label = "list-else"
insert_text = """list sequence as item>
    Part repeated for each item
<#else>
    Part executed when there are 0 items
</#list>"""
documentation = """
The `<#list>` directive, see the [directive reference](https://freemarker.apache.org/docs/ref_directive_list.html) for more info.

---
## Examples
```
<#list sequence as item>
    Part repeated for each item
<#else>
    Part executed when there are 0 items
</#list>
```
"""
