category = "directive"
label = "switch"
insert_text = """switch value>
  <#on "alice">
    ... (Handles "alice")
  <#on "bob", "carol">
    ... (Handles both "bob" and "carol")
  <#default>
    ...
</#switch>"""
documentation = """
The __recommended__ *`on`-based* form `<#switch>` directive , see the [directive reference](https://freemarker.apache.org/docs/ref_directive_switch.html) for more info.

---
## Examples
```
<#switch animal.size>
  <#on "small">
     Processed if animal.size was "small" 
  <#on "medium">
     Processed if animal.size was "medium" 
  <#on "large", "extra large">
     Processed if animal.size was "large" or "extra large"
  <#default>
     Processed if animal.size is neither of the above
</#switch>
```
"""
[label_details]
detail = "(on)"
description = "recommended"
